apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.


  annotations:
    "humanitec.com/orgId": "__HUMANITEC_ORG_ID__"
    "humanitec.com/appId": "backstage"

spec:
  type: website
  owner: user:guest
  lifecycle: experimental
